### ISSUE TITLE
Create quotes table

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/sunnah10#113]
```
One that is part of tafsir table. These ones will just randomly pop up from the 
side for appropriate hadith.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 19 Jul 2014 at 11:58

**Comment by canadainc** [comment]
![img-20150626-wa000](https://cloud.githubusercontent.com/assets/7464039/17008772/805f063a-4ec2-11e6-8728-fb8584780c8c.jpg)
![img-20150630-wa001](https://cloud.githubusercontent.com/assets/7464039/17008773/806b16be-4ec2-11e6-9110-a223398ba462.jpg)

**Comment by canadainc** [comment]
![img-20150805-wa002](https://cloud.githubusercontent.com/assets/7464039/17008792/b9511a96-4ec2-11e6-8a64-74f67f41e4ef.jpg)
![img-20150805-wa006](https://cloud.githubusercontent.com/assets/7464039/17008801/c5aea434-4ec2-11e6-8765-f9b6b99d444c.jpg)

**Comment by canadainc** [comment]
![img-20150812-wa005](https://cloud.githubusercontent.com/assets/7464039/17008845/28cdb640-4ec3-11e6-8e22-bd5412e32f04.jpg)
![img-20150818-wa000](https://cloud.githubusercontent.com/assets/7464039/17008873/5efbdac6-4ec3-11e6-99e5-02c56b10f884.jpg)

**Comment by canadainc** [comment]
![img-20150903-wa000](https://cloud.githubusercontent.com/assets/7464039/17008907/b9e10560-4ec3-11e6-8b42-87c0ee0abfea.jpg)
![img-20150903-wa002](https://cloud.githubusercontent.com/assets/7464039/17008909/c19ae9f6-4ec3-11e6-89d1-77fe42826c18.jpg)

**Comment by canadainc** [comment]
![img-20150930-wa000](https://cloud.githubusercontent.com/assets/7464039/17008977/59aa30f8-4ec4-11e6-81e2-d66136fe41c5.jpg)

**Comment by canadainc** [comment]
![img-20151009-wa005](https://cloud.githubusercontent.com/assets/7464039/17009005/ad8d1c1c-4ec4-11e6-9eb7-8e1db99ac4df.jpg)
![img-20151010-wa000](https://cloud.githubusercontent.com/assets/7464039/17009009/b5626a82-4ec4-11e6-9a8a-748eef760ad3.jpg)
![img-20151012-wa001](https://cloud.githubusercontent.com/assets/7464039/17009018/c858c3e8-4ec4-11e6-8923-14f966481fb5.jpg)
![img-20151012-wa000](https://cloud.githubusercontent.com/assets/7464039/17009023/d2ef0182-4ec4-11e6-9b23-2253cae20483.jpg)
![img-20151013-wa001](https://cloud.githubusercontent.com/assets/7464039/17009029/e050476e-4ec4-11e6-99c1-a9d26b443525.jpg)

**Comment by canadainc** [comment]
![img-20151019-wa006](https://cloud.githubusercontent.com/assets/7464039/17009064/2d7e4d56-4ec5-11e6-9385-fa906a124898.jpg)
![img-20151031-wa000](https://cloud.githubusercontent.com/assets/7464039/17009146/ddc028a6-4ec5-11e6-86a3-6fcbbcf10ffc.jpg)

**Comment by canadainc** [comment]
![img-20151031-wa002](https://cloud.githubusercontent.com/assets/7464039/17009155/f8c86988-4ec5-11e6-82f0-00198c476b0c.jpg)
![img-20151101-wa000](https://cloud.githubusercontent.com/assets/7464039/17009160/056b4ef8-4ec6-11e6-98bb-29d2ea8ab376.jpg)

**Comment by canadainc** [comment]
![img-20151111-wa000](https://cloud.githubusercontent.com/assets/7464039/17009231/98fb3b7e-4ec6-11e6-94e1-6d8355249d0f.jpg)

**Comment by canadainc** [comment]
“Abu Idris Al-Khawlani (rahimahullah) said: ”It is more beloved to me that I see fire in the masjid and not able to extinguish it, rather than see bid'ah in it and not able to stop it.” 

~ (al-Ibanah of Ibn Battah: 599)
