### ISSUE TITLE
Integrate Saheeh Al-Adab al-Mufrad additions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/sunnah10#168]
```
http://www.troid.ca/index.php/authors/the-salaf-scholars-of-the-salaf/229-muhamm
ad-ibn-ismaaeel-al-bukhaaree/256-extracts-from-saheeh-al-adab-al-mufrad-of-imaam
-bukhaaree
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 12 Oct 2014 at 1:33

**Comment by canadainc** [comment]
https://www.sayingsofthesalaf.net/hospitality-and-sharing-how-the-salaf-lived/

**Comment by canadainc** [comment]
https://www.sayingsofthesalaf.net/to-eat-a-dead-mule/

**Comment by canadainc** [comment]
https://www.sayingsofthesalaf.net/dhikr-and-sleep/

**Comment by canadainc** [comment]
http://www.salafibookstore.com/sbs/new/sbs.cfm?scn=productsdisplay&catID=2&subID=0&prodID=393

**Comment by canadainc** [comment]
Ibn Abbas: If the Pharaoh said to me: "Allah bless you." I would surely say: "And [bless] you too!" 
Al-Adab Al-Mufrad 1113, Sahihah 2/329.
https://twitter.com/AbuKhadeejahSP/status/483922456059871232

**Comment by canadainc** [comment]
https://www.sayingsofthesalaf.net/going-out-to-spread-greetings/

**Comment by canadainc** [comment]
https://www.sayingsofthesalaf.net/styles-of-charity-aishah-and-asma/

**Comment by canadainc** [comment]
http://www.sallallahualaihiwasallam.com/hadith-on-quran-the-prophet-would-recite-as-sajda-and-al-mulk-before-sleeping/
