### ISSUE TITLE
Integrate Sunan Ad-Darimi

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/sunnah10#175]
the author’s full name being ‘Abd Allah ibn ‘Abd al-Rahman al-Darimi (181H–255H), his Sunan is a hadith collection among the other prominent collections such as the Muwatta’ of Imam Malik and the Musnad of Imam Ahmad, etc. Despite its title as a Musnad, it is not arranged by narrator in the manner of other musnads, such as that of Tayalisi or Ibn Hanbal. It is arranged by subject matter in the manner of a book of Sunan, like the Sunan Ibn Majah

Original issue reported on code.google.com by `canadai...@gmail.com` on 12 Jan 2015 at 8:33

Attachments:
- [darimi_hadith.7z](https://storage.googleapis.com/google-code-attachments/sunnah10/issue-175/comment-0/darimi_hadith.7z)

**Comment by canadainc** [comment]
[darimi_7z.zip](https://github.com/canadainc/sunnah10/files/211701/darimi_7z.zip)

**Comment by canadainc** [comment]
http://www.salaficentre.com/2014/09/11-advice-for-the-seekers-of-knowledge-beware-of-التنَطُّع-التعمُّق-and-بدع/

**Comment by canadainc** [comment]
Abdul Azeez Bin Rabee (rahimahullaah) said:

Ataa (rahimahullaah) was asked about something, so he said: ”I don’t know.” He (Abdul Azeez) said, (then) it was said to him (i.e. Ataa), ”Do you not speak about it with your own opinion?” He (Ataa) said: I feel shy of Allaah (The Mighty and Majestic) to be (slave and worshipper) in the earth with my opinion/s. [Reported by Imaam Daarimee in his sunan: 1/108]



http://www.salaficentre.com/2012/07/look-at-how-abu-usaamah-the-greenlane-khateeb-of-desires-started-in-2002/

**Comment by canadainc** [comment]
http://mpubs.org/ibaadah/1035-reminders-quotes-dhul-hijjah-reminders-1437-exert-yourself-to-perform-righteous-acts-during-the-first-ten-day-of-dhul-hujjah-sa-eed-ibn-jubayr

**Comment by canadainc** [comment]
https://www.sayingsofthesalaf.net/at-the-doorstep-of-knowledge/

**Comment by canadainc** [comment]
http://shamela.ws/browse.php/book-21795#page-130

**Comment by canadainc** [comment]
https://www.sayingsofthesalaf.net/greetings-of-the-companions-a-little-known-sunnah/

**Comment by canadainc** [comment]
https://twitter.com/AbooMaryamm/status/387943324126281728
“Do not sit with the people of innovation and desires, nor argue with them, nor listen to them.” 

● Hasan al-Basrī [Sunan Ad-Dārimī, 1/121]

**Comment by canadainc** [comment]
https://twitter.com/AbooRuqayyahAMK/status/661634161258688514
Ibn ‘Abbaas:

“Upon you is the fear of Allaah and steadfastness. Follow and do not innovate.”

[Sunan ad-Daarimee, (p. 139)]

**Comment by canadainc** [comment]
1 – Ibn ‘Abbas reported that the Messenger of Allah said: “Do not enter upon your women when returning from a journey at night.”

He then narrated that the Messenger of Allah returned once with a caravan at night, whereupon two men with him slipped away and secretly went to their families, even though they had heard the Prophet forbidding them from doing so. Subsequently, both of them found a man with his wife.

[‘Sunan ad-Darimi‘ (444), and it is authentic]
