### ISSUE TITLE
Muwatta Malik enhancements

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/sunnah10#177]
```
Linking
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 12 Jan 2015 at 8:36

Attachments:
- [malik_hadith.7z](https://storage.googleapis.com/google-code-attachments/sunnah10/issue-177/comment-0/malik_hadith.7z)

**Comment by canadainc** [comment]
http://www.sallallahualaihiwasallam.com/hadith-on-punishment-repentance-in-secret-is-accepted-to-avoid-legal-punishment/
