### ISSUE TITLE
Jami at-Tirmidhi enhancements

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/sunnah10#180]
```
Linking
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 12 Jan 2015 at 8:37

Attachments:
- [tirmidhi_hadith.7z](https://storage.googleapis.com/google-code-attachments/sunnah10/issue-180/comment-0/tirmidhi_hadith.7z)

**Comment by canadainc** [comment]
https://twitter.com/AbooSufyaan/status/774916101088145408

**Comment by canadainc** [comment]
https://twitter.com/nooralfurqaan/status/702452163608506368

**Comment by canadainc** [comment]
https://archive.org/details/JamiAtTirmidhiVol.632913956EnglishArabic

**Comment by canadainc** [comment]
http://shamela.ws/browse.php/book-782#page-1

**Comment by canadainc** [comment]
http://shamela.ws/browse.php/book-7895#page-6917

**Comment by canadainc** [comment]
http://shamela.ws/browse.php/book-1435#page-6463
