### ISSUE TITLE
Implement scholar biographies

### ISSUE THREAD

**Issue by canadainc** [canadainc/sunnah10#207]
Info on scholars.
[ms_7z.zip](https://github.com/canadainc/sunnah10/files/248158/ms_7z.zip)

**Comment by canadainc** [comment]
http://biographie-savant-salaf-salih-pieux-predecesseurs.over-blog.com/

**Comment by canadainc** [comment]
https://twitter.com/aburemlah/status/779596782590423040

**Comment by canadainc** [comment]
https://twitter.com/aburemlah/status/773413195981713408

**Comment by canadainc** [comment]
https://musamills.wordpress.com/2007/08/16/shaikh-wasee-ullaah-abbaas/

**Comment by ilmtest** [comment]
http://mtws.posthaven.com/who-is-shaykh-alee-al-haddaadee

**Comment by ilmtest** [comment]
http://mtws.posthaven.com/veiled-sisters-uploading-their-pictures-on-th

**Comment by ilmtest** [comment]
http://mtws.posthaven.com/the-scholar-of-kuwait

**Comment by ilmtest** [comment]
http://mtws.posthaven.com/shaykh-fuaad-al-amree

**Comment by ilmtest** [comment]
http://mtws.posthaven.com/tazkiyah-from-shaykh-rabee-for-shaykh-abu-taariq-az-zubair-kerala-india

**Comment by ilmtest** [comment]
http://mtws.posthaven.com/the-birth-of-jesus-the-son-of-maryam-narrated-from-sahih-muslim-explained-by-shaykh-umar-fullatah

**Comment by ilmtest** [comment]
http://mtws.posthaven.com/tazkiyah-of-shaykh-muhammad-al-anjaree-for-shaykh-aboo-taariq-az-zubayr-and-shaykh-haneef-ibn-waa-waa-of-india

**Comment by ilmtest** [comment]
http://mtws.posthaven.com/sh-fawaaz-al-madkhalee-transmit-the-tazkiyah-of-shaykh-zayd-al-madkhalee-for-shaykh-muhammad-akkoor-and-others

**Comment by ilmtest** [comment]
Who is Shaykh Taariq As Subayee? ↓
http://mtws.posthaven.com/the-scholar-of-kuwait
http://www.salafitalk.net/st/viewmessages.cfm?forum=32&topic=12018

**Comment by ilmtest** [comment]
http://mtws.posthaven.com/shaykh-yahyaa-at-taalibee-recites-lines-of-poetry-by-shaykh-ahmad-an-najmee-regarding-things-which-were-specific-to-the-prophet-muhammad-over-other-prophets-upon-them-all-be-peace

**Comment by ilmtest** [comment]
http://mtws.posthaven.com/shaykh-muhammad-bin-haadee-according-to-the-testimony-of-the-senior-scholars

**Comment by ilmtest** [comment]
http://mtws.posthaven.com/salafi-scholars-who-speak-slowly-and-are-easy-to-understand
