### ISSUE TITLE
Integrate Tanbihul Ghafileen

### ISSUE THREAD

**Issue by canadainc** [canadainc/sunnah10#304]
Al-Hasan al Basri said:
  “Amazing is he who laughs, even though the Fire is in front of him, and feels elation, while death is awaiting him!”
-(Tanbihul-Ghafilin, vol.1, p.212)

Al-Ḥasan al-Baṣri once saw a man eating in the graveyard and commented,
“This is a hypocrite; he sees death before his eyes, yet his stomach craves for food.”
Tanbihu Al-Ghafilin, vol. 2, p. 617

https://tawheedmovement.files.wordpress.com/2013/02/the-wise-sayings-of-hasan-al-basri.pdf

**Comment by ilmtest** [comment]
https://twitter.com/RahaBatts/status/446307354251116544
