### ISSUE TITLE
Additional tafsir tracking

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/sunnah10#46]
```
http://salaficentre.com/2014/04/ustaadh-abu-khadeejah-may-allaah-preserve-him-on
-yasir-qadhi-and-al-maghrib-institute/
```

https://twitter.com/MarkazMuaadh/status/799259321905414144
https://twitter.com/MarkazMuaadh/status/799353676364034048

Original issue reported on code.google.com by `canadai...@gmail.com` on 14 Jun 2014 at 11:56

**Comment by canadainc** [comment]
![img-20150904-wa000](https://cloud.githubusercontent.com/assets/7464039/17008921/ea44f162-4ec3-11e6-96d7-ef1a588947ea.jpg)

**Comment by canadainc** [comment]
![img-20151016-wa001](https://cloud.githubusercontent.com/assets/7464039/17009040/fdd48eee-4ec4-11e6-9de9-b6c972ad47c4.jpg)

**Comment by canadainc** [comment]
![img-20151019-wa005](https://cloud.githubusercontent.com/assets/7464039/17009057/23a39c46-4ec5-11e6-9e0d-dd200b12f3eb.jpg)

**Comment by canadainc** [comment]
https://ksreminders.wordpress.com/

**Comment by canadainc** [comment]
http://authentic-translations.com/trans-pub

**Comment by canadainc** [comment]
https://twitter.com/AbooSufyaan/status/239866596825387009
https://twitter.com/AbooSufyaan/status/239868378309881856

**Comment by canadainc** [comment]
https://islam.stackexchange.com/questions/35749/is-al-hakims-hadith-collection-al-mustadrak-reliable

**Comment by canadainc** [comment]
http://maniacmuslim.ipbhost.com/topic/6945-im-really-stupid-and-ignorant-really/

https://ksreminders.wordpress.com/

https://iqtidaassirat.wordpress.com/2016/08/01/the-call-of-imam-abdullah-ibn-mubarak-shaykh-zubair-ali-z/

https://daralnicosia.wordpress.com/2011/05/02/7-hadiths-on-the-angel-of-death/

https://www.facebook.com/158667670835254/photos/a.158727630829258.26651.158667670835254/403550999680252/?type=3

https://www.facebook.com/permalink.php?story_fbid=501362599899091&id=158667670835254&substory_index=0

**Comment by canadainc** [comment]
Shaykh Abdur-Rahman as-Sa'di:
"The person who makes fun of others is often times worse than them. To make fun of people only springs from a heart that is full of bad characters."
(Taysir-ul-Karim, p. 801)

https://www.facebook.com/permalink.php?story_fbid=582610895107594&id=158667670835254

على إعجاب الساخر بنفسه، وعسى أن يكون المسخور به خيرًا من الساخر، كما هو الغالب والواقع، فإن السخرية، لا تقع إلا من قلب ممتلئ من مساوئ الأخلاق

http://shamela.ws/browse.php/book-42/page-1829#page-1829

**Comment by canadainc** [comment]
https://abenefitaday.wordpress.com/2012/03/10/tafseer-suratul-mulk-3/
https://abenefitaday.wordpress.com/2011/10/21/tafseer-suratul-mulk-2/

**Comment by canadainc** [comment]
https://abenefitaday.wordpress.com/2012/04/28/2nd-3rd-divorce-fataawa-of-sheikh-abdulmuhsin-abbaad/
