### ISSUE TITLE
Integrate Musnad Imam Ahmad

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/sunnah10#65]
```
https://archive.org/download/MusnadAhmadBinHanbalArabicEnglishTranslation/Musnad
%20Ahmad%20Bin%20Hanbal%2C%20Arabic%20-English%20Translation-Volume%201_text.pdf

https://archive.org/download/MusnadAhmadBinHanbalArabicEnglishTranslation/Musnad
%20Ahmad%20Bin%20Hanbal%2C%20Arabic%20-English%20Translation-Volume%203_text.pdf

https://archive.org/download/MusnadAhmadBinHanbalArabicEnglishTranslation/Musnad
%20Ahmad%20Bin%20Hanbal%2C%20Arabic%20-English%20Translation-Volume%202_text.pdf
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 7 Jul 2014 at 4:45

**Comment by canadainc** [comment]
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Arabic` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Arabic` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Arabic` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Arabic` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT * FROM Arabic INNER JOIN Hadiths_content ON Arabic.ROWID=Hadiths_content.ROWID);
SELECT * FROM Arabic INNER JOIN Hadiths_content ON Arabic.ROWID=Hadiths_content.ROWID LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT narrator_ar,c3text FROM Arabic INNER JOIN Hadiths_content ON Arabic.ROWID=Hadiths_content.ROWID);
SELECT narrator_ar,c3text FROM Arabic INNER JOIN Hadiths_content ON Arabic.ROWID=Hadiths_content.ROWID LIMIT 0, 50000;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT narrator_ar,text_ar,c3text FROM Arabic INNER JOIN Hadiths_content ON Arabic.ROWID=Hadiths_content.ROWID);
SELECT narrator_ar,text_ar,c3text FROM Arabic INNER JOIN Hadiths_content ON Arabic.ROWID=Hadiths_content.ROWID LIMIT 0, 50000;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Arabic` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Arabic` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Arabic` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Arabic` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Hadiths_segments` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Hadiths_segments` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Hadiths_segdir` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Hadiths_segdir` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Book` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Book` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Arabic` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Arabic` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `Arabic` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `Arabic` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `merged` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `merged` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
DROP TABLE `Arabic`;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `merged` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `merged` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
DROP TABLE `Hadiths_content`;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `merged` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `merged` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
DROP TABLE `Hadiths`;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `merged` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `merged` ORDER BY `_rowid_` ASC LIMIT 0, 50000;
DROP TABLE `android_metadata`;
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `merged` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `merged` ORDER BY `_rowid_` ASC LIMIT 0, 50000;

**Comment by canadainc** [comment]
DELETE FROM Book WHERE CollectionID <> 8
DELETE FROM merged WHERE c0CollectionID <> 8
[hadith.7z.zip](https://github.com/canadainc/sunnah10/files/220258/hadith.7z.zip)

**Comment by canadainc** [comment]
https://archive.org/details/musnad-imam-ahmad-bin-hanbal-volume-1-3

**Comment by canadainc** [comment]
https://archive.org/details/EnglishTranslationOfMusnadImamAhmedBinHanbalVolume1

**Comment by canadainc** [comment]
http://hadith.al-islam.com/Page.aspx?pageid=192&TOCID=4&BookID=30&PID=5

**Comment by canadainc** [comment]
musnad plain text
[plain_text.7z.zip](https://github.com/canadainc/sunnah10/files/253738/plain_text.7z.zip)

**Comment by canadainc** [comment]
http://shamela.ws/browse.php/book-98139#page-165

**Comment by canadainc** [comment]
http://uponistiqaamah.blogspot.ca/2011/03/best-way-for-sisters-to-say.html?m=1
