### ISSUE TITLE
Implement fabricated hadith tab

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/sunnah10#87]
```
Put all popular fabricated narrations there
http://asma-wa-sifaat.com/2013/08/06/the-heart-of-my-believing-servant-can-conta
in-me-baseless-lie-attributed-to-allaah-as-a-hadeeth-qudsee/
```
Original issue reported on code.google.com by `canadai...@gmail.com` on 15 Jul 2014 at 2:37

**Comment by canadainc** [comment]
http://islamport.com/l/alb/2455/1.htm

**Comment by canadainc** [comment]
http://tahirbinmansoor.tumblr.com/post/151560533025/some-fabricated-ahaadeeth-collected-by-shaykh

**Comment by canadainc** [comment]
https://twitter.com/AbrarAsSalafi/status/819914349502402561

**Comment by canadainc** [comment]
https://twitter.com/ali_aub75/status/311095139118481408

**Comment by canadainc** [comment]
https://twitter.com/AbuZikraBilal/status/259415967304658944

**Comment by canadainc** [comment]
https://twitter.com/YasinMMunye/status/751771651214340096

**Comment by canadainc** [comment]
https://twitter.com/TahirBinMansoor/status/774905020168843264

**Comment by canadainc** [comment]
https://twitter.com/TahirBinMansoor/status/776754257483542528

**Comment by canadainc** [comment]
https://twitter.com/TahirBinMansoor/status/773360044238737408

**Comment by canadainc** [comment]
https://twitter.com/TahirBinMansoor/status/767324827313070081

**Comment by canadainc** [comment]
https://twitter.com/TahirBinMansoor/status/762158528500871168

**Comment by canadainc** [comment]
https://twitter.com/TahirBinMansoor/status/761939637644341248

**Comment by canadainc** [comment]
https://twitter.com/TahirBinMansoor/status/761153612097650688

**Comment by canadainc** [comment]
https://twitter.com/zahacktanvir/status/732562455692464130

**Comment by canadainc** [comment]
https://twitter.com/AbuScarface/status/697892807583907840

**Comment by canadainc** [comment]
https://twitter.com/EL__Haqq/status/590972065060106241

**Comment by canadainc** [comment]
https://twitter.com/Element_AA/status/329015159681077248

**Comment by canadainc** [comment]
https://twitter.com/mwarsame1/status/295474486948548609

**Comment by canadainc** [comment]
https://twitter.com/ibnbaraa/status/799412344346394624
https://www.facebook.com/permalink.php?story_fbid=1152369244853617&id=490751374348744

**Comment by canadainc** [comment]
https://twitter.com/maktabah/status/226799860769255425

**Comment by canadainc** [comment]
https://twitter.com/AbuHakeemBilal/status/484712765131874304

**Comment by canadainc** [comment]
https://twitter.com/AbuHakeemBilal/status/785800250241929217

**Comment by canadainc** [comment]
https://saaid.net/Doat/ehsan/100_Hadith.doc

**Comment by canadainc** [comment]
https://www.scribd.com/doc/109509558/125-Weak-and-Fabricated-Hadeeth
